blank_issues_enabled: true
issue_templates:
  - name: 'ğŸ› ï¸ [CHORE] TODO'
    about: 'Frontend Issue - chore'
    title: '[CHORE] '
    labels: ['chore']
    assignees: []
  - name: 'ğŸ–¥ï¸ [FEATURE] TODO'
    about: 'Frontend Issue - feature'
    title: '[FEATURE] '
    labels: ['feature']
    assignees: []
  - name: 'ğŸš¨ [FIX] TODO'
    about: 'Frontend Issue - fix'
    title: '[FIX] '
    labels: ['fix']
    assignees: []
  - name: 'ğŸ§¹ [REFACTORING] TODO'
    about: 'Frontend Issue - refactoring'
    title: '[REFACTORING] '
    labels: ['refactoring']
    assignees: []
